### ISSUE TITLE
Wired.com

### ISSUE THREAD

**Issue by jgenender** [reek/anti-adblock-killer#1049]
http://www.wired.com/2016/02/absurd-creature-of-the-week-the-huge-bee-decapitating-that-hornet-cant-survive-group-hugs/

No surprises on this one ;-)  Get a nice big "Here’s The Thing With Ad Blockers" covering the text using a "veil-active" class.  div id="veil" can be stricken but the scroll is shut off.

Browsers: Firefox 44.0.2 (MacOSX) and Chrome 48.0.2564.109 (64 bit)  (MacOSX)
Greasemonkey 3.6 (Firefox) and Tapermonkey 3.12.58 (Chrome)
Adblock Plus (Firefox and Chrome)
EasyList + AakList

**Comment by chadthman** [comment]
The scrolling is disabled by the `no-scroll` class added on the `<body>` tag

**Comment by jgenender** [comment]
Ok... so the veil is removed with this:

www.wired.com##DIV#veil

The no-scroll seems to activate about 5-10 seconds on the page.  I have nee trying to write a rule to prevent it, but nothing working as of yet...

**Comment by jgenender** [comment]
Ok... with the Stylish plugin, this bit of code makes it work along with the filter for adblock above:

```
@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document domain("wired.com") {  
  .no-scroll {
    overflow: scroll !important;
  }
}
```

It would be nice to have all of this work as a filter ;-)

**Comment by jgenender** [comment]
and for Chrome users... use Stylish and add a Wired script with the following for URL with domain wired.com:

 ```
 .no-scroll {
    overflow: scroll !important;
  }
```

**Comment by paradox460** [comment]
Don't just globally disable no-scroll, wired uses it for some of their galleries.

```css
body.no-scroll {
  overflow: auto !important;
}
```

This seems to do the trick, and doesn't break other site elements

**Comment by jgenender** [comment]
Even better! ;-) Gratzi!

**Comment by jgenender** [comment]
Actually... this can all be completed in Stylish:

For Firefox:

@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document domain("wired.com") {  
body.no-scroll {
    overflow: auto !important;
}
#veil {
    display: none !important;
}
}

and for Chrome on URLs of domain wired.com:

body.no-scroll {
    overflow: auto !important;
}
#veil {
    display: none !important;
}
}

**Comment by Arokhantos** [comment]
Actually disabled javascript on wired.com and popup is gone.

**Comment by fncll** [comment]
The Chrome solution doesn't work for me. It does hide the overlay, but all the text disappears as well. running Chrome 48.0.2564.109 (64-bit)

**Comment by jgenender** [comment]
Yeah... wired just changed it today.  This needs a new solution.

**Comment by Arokhantos** [comment]
Just block javascript on wired.com popup gone then, ofcourse probably may need better solution still the popup needs javascript appearntly.

**Comment by jgenender** [comment]
You lose the ability to see some images/galleries.  So yeah, you can read the article, but it renders some of the site useless, so that is not a long term viable option.

**Comment by jgenender** [comment]
Ok... from what I can tell, the offending piece of code appears to be in their ads.js or ads.min.js,  However, they are using wordpress and they appear to be using a load?scripts proxy call that concatenates a lot of javascript files to make one big javascript load.  The offending script appears to be located in the main html here:

`<script type='text/javascript' src='http://www.wired.com/assets/load?scripts=true&amp;c=1&amp;load%5B%5D=jquery-sonar,wpcom-lazy-load-images,outbrain,tracking,ads,wired&amp;ver=1455828505'></script>`

I think if ublock or other can turn that into this:

`<script type='text/javascript' src='http://www.wired.com/assets/load?scripts=true&amp;c=1&amp;load%5B%5D=jquery-sonar,wpcom-lazy-load-images,wired&amp;ver=1455828505'></script>`

We may have a winner.

**Comment by akadrac** [comment]
created a quick and dirty userscript @ https://github.com/akadrac/aa-wired for use with greasemonkey, etc

**Comment by jgenender** [comment]
Awesome.... did you get it to work?  Its not swapping out the html for me...

**Comment by jgenender** [comment]
Ok... its working great on Chrome ;-)  Trying to get FF to work...

**Comment by jgenender** [comment]
akadrac, nice job!  Got FF to work too... it seems that uBlock Origin plus your script does it for now. ;-)

All images and other widgets are working fine.

Ok wired... your move...

**Comment by D-Smoke** [comment]
I don't even go on wired that much, but I hate when sites do this. Installed your script akadrac on FF greasemonkey. I'm still getting adblock nag after clearing cookies and cache. Script is enabled in greasemonkey.

**Comment by billreed63** [comment]
The script works for me on Chrome, I had to restart my browser

**Comment by IDKwhattoputhere** [comment]
Isn't it fixed in uBlock Origin? https://github.com/gorhill/uBlock/commit/ce2d235e4fd2ade2be101fa7030870044b30fd3c

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by chadthman** [comment]
@akadrac's script works Chrome for now. It's still not working in Safari and unfortunately there is no uBlock Origin for Safari at the moment.

**Comment by reek** [comment]
Hi all,

can you tested this version.
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by chadthman** [comment]
Seems to work on Both Chrome and Safari under OS 10.11.2. However if you did navigate to the site before having this in place you will now get a "Thank you for not using ad block" message that might be hidden if you blocked the `veil` div from showing using adblock and it will result in just putting the `no-scroll ` class in place causing the user to not being able to scroll.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
