### ISSUE TITLE
sc2casts.com

### ISSUE THREAD

**Issue by Shakos** [reek/anti-adblock-killer#880]
http://sc2casts.com/
https://i.imgur.com/k7dDvtu.jpg
Firefox 43.0.2
No script manager
uBlock₀
Anti-Adblock Killer | Reek‎  (github.com), EasyList‎ (forums.lanik.us), Peter Lowe’s Ad server list‎ (pgl.yoyo.org)

Thank you! It used to work but I believe it was patched.

**Comment by Giwayume** [comment]
Hahaha they put a random class name and id on that popup. They're really desperate.

**Comment by Giwayume** [comment]
Here is a solution using content sniffing, maybe not the fastest:
```
    sc2casts_com : {
      host : ['sc2casts.com'],
      onBeforeScript : function (e) { // disable analytics, reports adblock
        if (Aak.contains(Aak.innerScript(e), 'google-analytics.com')) {
          Aak.stopScript(e);
        }
      },
      onIdle : function() {
        var divs = document.querySelectorAll('div');
        for (var i=0, il=divs.length; i<il; i++) {
          if (Aak.contains(divs[i].innerHTML.toLowerCase(), 'adblock') && divs[i].parentNode) {
            divs[i].parentNode.removeChild(divs[i]);
          }
        }
      }
    },
```

**Comment by reek** [comment]
@Shakos 
Already fixed by
<pre>
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=sc2casts.com
@@||pagead2.googlesyndication.com/pagead/js/r*/r*/show_ads_impl.js$script,domain=sc2casts.com
</pre>

**Comment by Giwayume** [comment]
Nope, those filters are already in place, they've implemented a new popup that's inline in their code.

I'm subscribed to the latest list which has those two filters, and still get the popup mentioned by Shakos.

**Comment by reek** [comment]
@Giwayume 
weird, I have nothing at all :/

**Comment by Giwayume** [comment]
You should see markup that looks like this when viewing source on the page (the modal):
```
<div class="JACEN"><div class="hmQgm"><!--<div style="color:red;vertical-align:middle;font-size:16px;margin-left:25px;">If SC2Casts looks broken, functionality doesn't work or it doesn't stop loading - it's because of your adblock!</div>--><div class="headline"><div style="display:inline-block;float:right;color:#ccc" id="ccd">[5]</div><br><div style="font-size:14px;">You are getting this popup because you're using AdBlock (or something similar)</div></div><br><br><!--Hey there. This is Santah - the single developer who created SC2Casts (more than 5 years ago).<br><br>Ever since then I'm working daily on supporting and improving the site, while keeping it clean and functional.<br><br>During those 5 years, I haven't missed a single day of updating the site for daily VODs - even on my wedding or when my kids were born! :D I will keep SC2Casts running for many more years and will update it with the best content available, but I need your help guys.<br><br>-->For ads-free experience, please <!--consider trying (for free!)--> check out <a href='/premium' style='color:#FF8335'>SC2Casts Premium</a> - for the price of 2 movie tickets a year this will remove the ads and will give you awesome new functionality which will only get better<!-- (and more expensive for new members)-->.<br><br>Another option is to simply whitelist SC2Casts in your Adblock - <a href="http://blog.tordeu.com/?p=4" target="_blank" style="color:brown">see how here</a>. Make sure you whitelist in all your adblock extensions.<br><br>Thank you!<br><br><div style="color:#666;text-align:right">If you believe you're getting this in error - please <a href="mailto:info@sc2casts.com" style="color:brown">get in touch</a> and we'll solve this right away!</div></div></div><div class="JJhVL"></div>
```
And there's also some inline script tags which define a few functions that display the modal `startCountDown()`, `updateTimer()`.

They actually check if the `show_ads_impl.js` is blocked and display the modal if it is:

```
var script = document.createElement('script');
	console.log("1");
    script.onerror = function(){
        script.onerror = null;
		
        document.body.removeChild(script);
		document.getElementById("Kubpz").style.display="";
		_gaq.push(['_trackEvent', 'adblock popup', "show popup", document.location+""]);
		startCountDown();
    }
    script.src = "http://pagead2.googlesyndication.com/pagead/js/r20150723/r20150728/show_ads_impl.js";
    document.body.appendChild(script);
```

**Comment by reek** [comment]
@Giwayume 
I tested with Firefox/uBlock and Chrome/uBlock and the two filters work.

Try purge all caches and update

can you give me your list of extensions ?

**Comment by Giwayume** [comment]
Nevermind, it appears to be working in Chrome if I do a fresh install. Must be something with my Firefox.

**Comment by Shakos** [comment]
I purged the cache and made sure AAK was up to date but still am getting
the popups on Firefox. Does Chrome do something that Firefox isn't capable
of?

**Comment by reek** [comment]
my config uBlock
http://www40.zippyshare.com/v/GGm5WEPb/file.html

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer#help

**Comment by Shakos** [comment]
Ah I disabled this HTTPS Everywhere addon and it is working now. I feel like a fool. Thanks for all the help :)

**Comment by reek** [comment]
@Shakos 
Thank you for feedback, I will add it to the list of extension that may cause problems
